---
- name: Install opnsense packages
  community.general.pkgng:
    name: "{{ opn_packages }}"
    state: present

- name: install {{ checkmk_agent_name }} from server
  block:
    - name: download {{ checkmk_agent_name }} from server
      delegate_to: localhost
      check_mode: false
      run_once: true
      ansible.builtin.get_url:
        url: "{{ checkmk_proto }}://{{ checkmk_hostname }}/{{ checkmk_path }}/{{ checkmk_agent_name }}"
        dest: "{{ _local_tmp }}/{{ checkmk_agent_name }}"
        mode: "0600"

    - name: apply patches
      delegate_to: localhost
      check_mode: false
      run_once: true
      ansible.posix.patch:
        src: "{{ item }}"
        dest: "{{ _local_tmp }}/{{ checkmk_agent_name }}"
        remote_src: false
      with_items: "{{  opn_check_mk_patches | default([]) }}"

    - name: copy {{ checkmk_agent_name }} from {{ _local_tmp }}
      ansible.builtin.copy:
        src: "{{ _local_tmp }}/{{ checkmk_agent_name }}"
        dest: "{{ opn_check_mk_path }}"
        mode: 0700
      notify: service inetd
  when:
    - opn_install_check_mk | bool
    - checkmk_hostname is defined

- name: copy {{ checkmk_agent_name }} from local files
  ansible.builtin.copy:
    src: "{{ checkmk_agent_name }}"
    dest: "{{ opn_check_mk_path }}"
    mode: 0700
  notify: service inetd
  when:
    - opn_install_check_mk
    - checkmk_hostname is not defined

- name: create lib dirs
  ansible.builtin.file:
    path: "{{ opn_check_mk_lib_dir }}/{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - local
    - plugins
  when: opn_install_check_mk

- name: create check_mk plugins cache dirs
  ansible.builtin.file:
    path: "{{ opn_check_mk_lib_dir }}/plugins/{{ item }}"
    state: directory
    mode: 0755
  with_items: "{{ opn_check_mk_plugins | map('dirname') | unique |}}"
  when:
    - opn_install_check_mk
    - item | length > 0

- name: copy check_mk plugins
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ opn_check_mk_lib_dir }}/plugins/{{ item }}"
    mode: 0700
  with_items: "{{ opn_check_mk_plugins }}"
  when: opn_install_check_mk

- name: create check_mk local checks cache dirs
  ansible.builtin.file:
    path: "{{ opn_check_mk_lib_dir }}/local/{{ item }}"
    state: directory
    mode: 0755
  with_items: "{{ opn_check_mk_local_checks | map('dirname') | unique }}"
  when:
    - opn_install_check_mk
    - item | length > 0

- name: copy check_mk local checks
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ opn_check_mk_lib_dir }}/local/{{ item }}"
    mode: 0700
  with_items: "{{ opn_check_mk_local_checks }}"
  when: opn_install_check_mk

- name: copy check_mk additional files
  ansible.builtin.copy:
    src: "{{ item.key }}"
    dest: "{{ item.value }}"
    mode: 0600
  with_dict: "{{ opn_check_mk_additional_files }}"
  when: opn_install_check_mk

- name: enable check_mk_agent in /etc/inetd.conf
  ansible.builtin.lineinfile:
    path: /etc/inetd.conf
    line: "check_mk  stream  tcp nowait  root  {{ opn_check_mk_path }} {{ opn_check_mk_path | basename }}"
    regexp: "^check_mk "
  notify: service inetd
  when: opn_install_check_mk

- name: add service to /etc/services
  ansible.builtin.lineinfile:
    path: /etc/services
    line: "check_mk	{{ opn_check_mk_port }}/tcp   #check_mk agent"  # noqa no-tabs
    regexp: "^check_mk "
  notify: service inetd
  when: opn_install_check_mk

- name: setup /etc/hosts.allow
  ansible.builtin.lineinfile:
    path: /etc/hosts.allow
    line: "check_mk	: {{ checkmk_ip }} : allow"  # noqa no-tabs
    regexp: "^check_mk "
  notify: service inetd
  when: opn_install_check_mk

- name: debug ansible_local
  ansible.builtin.debug:
    var: ansible_local
    verbosity: 1

- name: enable inetd
  ansible.builtin.blockinfile:
    backup: true
    path: /etc/rc.conf
    block: |
      inetd_enable=yes
      inetd_flags=-wW
    marker: "# -- {mark} ANSIBLE MANAGED BLOCK for inetd -->"
  when: ansible_local.opnsense.core.product_series|default(ansible_local.opnsense.core.product_abi) is version('21', '<')
  notify: service inetd

- name: enable inetd
  ansible.builtin.blockinfile:
    backup: true
    path: /etc/rc.conf.d/inetd
    create: true
    block: |
      inetd_enable=yes
      inetd_flags=-wW
    marker: "# -- {mark} ANSIBLE MANAGED BLOCK for inetd -->"
    owner: root
    group: wheel
    mode: 0644
  when: ansible_local.opnsense.core.product_series|default(ansible_local.opnsense.core.product_abi) is version('21', '>=')
  notify: service inetd

...
# vim: tabstop=2 expandtab shiftwidth=2 softtabstop=2 smartindent nu ft=yaml
