# vim: tabstop=2 expandtab shiftwidth=2 softtabstop=2 smartindent nu
---
name: ansible-lint
on:
  pull_request:
  push:
  schedule:
    - cron: "20 6 * * 1"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: run ansible-lint
        uses: ansible/ansible-lint@v24.2.1
