# vim: tabstop=2 expandtab shiftwidth=2 softtabstop=2 smartindent nu
---
name: pylint
on:
  pull_request:
  push:
  schedule:
    - cron: "20 6 * * 1"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: install pylint
        run: |
          python -m pip install --upgrade pip
          pip install pylint==2.7.2 pyyaml
      - name: run pylint
        run: |
          pylint files/*.py
